/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppOrganizationsIndexRouteImport } from './routes/_app/organizations/index'
import { Route as AppSettingsThemeRouteImport } from './routes/_app/settings/theme'
import { Route as AppSettingsLanguageRouteImport } from './routes/_app/settings/language'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'
import { Route as AppOrganizationsNewRouteImport } from './routes/_app/organizations/new'
import { Route as AppOrganizationsJoinRouteImport } from './routes/_app/organizations/join'
import { Route as AppOrganizationsOrganizationIdRouteImport } from './routes/_app/organizations/$organizationId'
import { Route as AppInvitesInviteIdRouteImport } from './routes/_app/invites/$inviteId'
import { Route as AppOrganizationsOrganizationIdIndexRouteImport } from './routes/_app/organizations/$organizationId/index'
import { Route as AppOrganizationsOrganizationIdOverviewRouteImport } from './routes/_app/organizations/$organizationId/overview'
import { Route as AppOrganizationsOrganizationIdSettingsIndexRouteImport } from './routes/_app/organizations/$organizationId/settings/index'
import { Route as AppOrganizationsOrganizationIdDiscussionsIndexRouteImport } from './routes/_app/organizations/$organizationId/discussions/index'
import { Route as AppOrganizationsOrganizationIdBoardsIndexRouteImport } from './routes/_app/organizations/$organizationId/boards/index'
import { Route as AppOrganizationsOrganizationIdSettingsGeneralRouteImport } from './routes/_app/organizations/$organizationId/settings/general'
import { Route as AppOrganizationsOrganizationIdDiscussionsNewRouteImport } from './routes/_app/organizations/$organizationId/discussions/new'
import { Route as AppOrganizationsOrganizationIdBoardsNewRouteImport } from './routes/_app/organizations/$organizationId/boards/new'
import { Route as AppOrganizationsOrganizationIdSettingsPeopleIndexRouteImport } from './routes/_app/organizations/$organizationId/settings/people/index'
import { Route as AppOrganizationsOrganizationIdSettingsInvitesIndexRouteImport } from './routes/_app/organizations/$organizationId/settings/invites/index'
import { Route as AppOrganizationsOrganizationIdDiscussionsDiscussionIdIndexRouteImport } from './routes/_app/organizations/$organizationId/discussions/$discussionId/index'
import { Route as AppOrganizationsOrganizationIdBoardsBoardIdIndexRouteImport } from './routes/_app/organizations/$organizationId/boards/$boardId/index'
import { Route as AppOrganizationsOrganizationIdSettingsInvitesNewRouteImport } from './routes/_app/organizations/$organizationId/settings/invites/new'
import { Route as AppOrganizationsOrganizationIdDiscussionsDiscussionIdEditRouteImport } from './routes/_app/organizations/$organizationId/discussions/$discussionId/edit'
import { Route as AppOrganizationsOrganizationIdBoardsBoardIdNewRouteImport } from './routes/_app/organizations/$organizationId/boards/$boardId/new'
import { Route as AppOrganizationsOrganizationIdBoardsBoardIdEditRouteImport } from './routes/_app/organizations/$organizationId/boards/$boardId/edit'
import { Route as AppOrganizationsOrganizationIdSettingsPeopleUserIdEditRouteImport } from './routes/_app/organizations/$organizationId/settings/people/$userId.edit'
import { Route as AppOrganizationsOrganizationIdDiscussionsDiscussionIdCommentIdEditRouteImport } from './routes/_app/organizations/$organizationId/discussions/$discussionId/$commentId.edit'
import { Route as AppOrganizationsOrganizationIdBoardsBoardIdTaskIdEditRouteImport } from './routes/_app/organizations/$organizationId/boards/$boardId/$taskId.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppOrganizationsIndexRoute = AppOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsThemeRoute = AppSettingsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsLanguageRoute = AppSettingsLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppOrganizationsNewRoute = AppOrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsJoinRoute = AppOrganizationsJoinRouteImport.update({
  id: '/organizations/join',
  path: '/organizations/join',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsOrganizationIdRoute =
  AppOrganizationsOrganizationIdRouteImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppInvitesInviteIdRoute = AppInvitesInviteIdRouteImport.update({
  id: '/invites/$inviteId',
  path: '/invites/$inviteId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsOrganizationIdIndexRoute =
  AppOrganizationsOrganizationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrganizationsOrganizationIdRoute,
  } as any)
const AppOrganizationsOrganizationIdOverviewRoute =
  AppOrganizationsOrganizationIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AppOrganizationsOrganizationIdRoute,
  } as any)
const AppOrganizationsOrganizationIdSettingsIndexRoute =
  AppOrganizationsOrganizationIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AppOrganizationsOrganizationIdRoute,
  } as any)
const AppOrganizationsOrganizationIdDiscussionsIndexRoute =
  AppOrganizationsOrganizationIdDiscussionsIndexRouteImport.update({
    id: '/discussions/',
    path: '/discussions/',
    getParentRoute: () => AppOrganizationsOrganizationIdRoute,
  } as any)
const AppOrganizationsOrganizationIdBoardsIndexRoute =
  AppOrganizationsOrganizationIdBoardsIndexRouteImport.update({
    id: '/boards/',
    path: '/boards/',
    getParentRoute: () => AppOrganizationsOrganizationIdRoute,
  } as any)
const AppOrganizationsOrganizationIdSettingsGeneralRoute =
  AppOrganizationsOrganizationIdSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => AppOrganizationsOrganizationIdRoute,
  } as any)
const AppOrganizationsOrganizationIdDiscussionsNewRoute =
  AppOrganizationsOrganizationIdDiscussionsNewRouteImport.update({
    id: '/discussions/new',
    path: '/discussions/new',
    getParentRoute: () => AppOrganizationsOrganizationIdRoute,
  } as any)
const AppOrganizationsOrganizationIdBoardsNewRoute =
  AppOrganizationsOrganizationIdBoardsNewRouteImport.update({
    id: '/boards/new',
    path: '/boards/new',
    getParentRoute: () => AppOrganizationsOrganizationIdRoute,
  } as any)
const AppOrganizationsOrganizationIdSettingsPeopleIndexRoute =
  AppOrganizationsOrganizationIdSettingsPeopleIndexRouteImport.update({
    id: '/settings/people/',
    path: '/settings/people/',
    getParentRoute: () => AppOrganizationsOrganizationIdRoute,
  } as any)
const AppOrganizationsOrganizationIdSettingsInvitesIndexRoute =
  AppOrganizationsOrganizationIdSettingsInvitesIndexRouteImport.update({
    id: '/settings/invites/',
    path: '/settings/invites/',
    getParentRoute: () => AppOrganizationsOrganizationIdRoute,
  } as any)
const AppOrganizationsOrganizationIdDiscussionsDiscussionIdIndexRoute =
  AppOrganizationsOrganizationIdDiscussionsDiscussionIdIndexRouteImport.update({
    id: '/discussions/$discussionId/',
    path: '/discussions/$discussionId/',
    getParentRoute: () => AppOrganizationsOrganizationIdRoute,
  } as any)
const AppOrganizationsOrganizationIdBoardsBoardIdIndexRoute =
  AppOrganizationsOrganizationIdBoardsBoardIdIndexRouteImport.update({
    id: '/boards/$boardId/',
    path: '/boards/$boardId/',
    getParentRoute: () => AppOrganizationsOrganizationIdRoute,
  } as any)
const AppOrganizationsOrganizationIdSettingsInvitesNewRoute =
  AppOrganizationsOrganizationIdSettingsInvitesNewRouteImport.update({
    id: '/settings/invites/new',
    path: '/settings/invites/new',
    getParentRoute: () => AppOrganizationsOrganizationIdRoute,
  } as any)
const AppOrganizationsOrganizationIdDiscussionsDiscussionIdEditRoute =
  AppOrganizationsOrganizationIdDiscussionsDiscussionIdEditRouteImport.update({
    id: '/discussions/$discussionId/edit',
    path: '/discussions/$discussionId/edit',
    getParentRoute: () => AppOrganizationsOrganizationIdRoute,
  } as any)
const AppOrganizationsOrganizationIdBoardsBoardIdNewRoute =
  AppOrganizationsOrganizationIdBoardsBoardIdNewRouteImport.update({
    id: '/boards/$boardId/new',
    path: '/boards/$boardId/new',
    getParentRoute: () => AppOrganizationsOrganizationIdRoute,
  } as any)
const AppOrganizationsOrganizationIdBoardsBoardIdEditRoute =
  AppOrganizationsOrganizationIdBoardsBoardIdEditRouteImport.update({
    id: '/boards/$boardId/edit',
    path: '/boards/$boardId/edit',
    getParentRoute: () => AppOrganizationsOrganizationIdRoute,
  } as any)
const AppOrganizationsOrganizationIdSettingsPeopleUserIdEditRoute =
  AppOrganizationsOrganizationIdSettingsPeopleUserIdEditRouteImport.update({
    id: '/settings/people/$userId/edit',
    path: '/settings/people/$userId/edit',
    getParentRoute: () => AppOrganizationsOrganizationIdRoute,
  } as any)
const AppOrganizationsOrganizationIdDiscussionsDiscussionIdCommentIdEditRoute =
  AppOrganizationsOrganizationIdDiscussionsDiscussionIdCommentIdEditRouteImport.update(
    {
      id: '/discussions/$discussionId/$commentId/edit',
      path: '/discussions/$discussionId/$commentId/edit',
      getParentRoute: () => AppOrganizationsOrganizationIdRoute,
    } as any,
  )
const AppOrganizationsOrganizationIdBoardsBoardIdTaskIdEditRoute =
  AppOrganizationsOrganizationIdBoardsBoardIdTaskIdEditRouteImport.update({
    id: '/boards/$boardId/$taskId/edit',
    path: '/boards/$boardId/$taskId/edit',
    getParentRoute: () => AppOrganizationsOrganizationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/invites/$inviteId': typeof AppInvitesInviteIdRoute
  '/organizations/$organizationId': typeof AppOrganizationsOrganizationIdRouteWithChildren
  '/organizations/join': typeof AppOrganizationsJoinRoute
  '/organizations/new': typeof AppOrganizationsNewRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/language': typeof AppSettingsLanguageRoute
  '/settings/theme': typeof AppSettingsThemeRoute
  '/organizations/': typeof AppOrganizationsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/organizations/$organizationId/overview': typeof AppOrganizationsOrganizationIdOverviewRoute
  '/organizations/$organizationId/': typeof AppOrganizationsOrganizationIdIndexRoute
  '/organizations/$organizationId/boards/new': typeof AppOrganizationsOrganizationIdBoardsNewRoute
  '/organizations/$organizationId/discussions/new': typeof AppOrganizationsOrganizationIdDiscussionsNewRoute
  '/organizations/$organizationId/settings/general': typeof AppOrganizationsOrganizationIdSettingsGeneralRoute
  '/organizations/$organizationId/boards/': typeof AppOrganizationsOrganizationIdBoardsIndexRoute
  '/organizations/$organizationId/discussions/': typeof AppOrganizationsOrganizationIdDiscussionsIndexRoute
  '/organizations/$organizationId/settings/': typeof AppOrganizationsOrganizationIdSettingsIndexRoute
  '/organizations/$organizationId/boards/$boardId/edit': typeof AppOrganizationsOrganizationIdBoardsBoardIdEditRoute
  '/organizations/$organizationId/boards/$boardId/new': typeof AppOrganizationsOrganizationIdBoardsBoardIdNewRoute
  '/organizations/$organizationId/discussions/$discussionId/edit': typeof AppOrganizationsOrganizationIdDiscussionsDiscussionIdEditRoute
  '/organizations/$organizationId/settings/invites/new': typeof AppOrganizationsOrganizationIdSettingsInvitesNewRoute
  '/organizations/$organizationId/boards/$boardId/': typeof AppOrganizationsOrganizationIdBoardsBoardIdIndexRoute
  '/organizations/$organizationId/discussions/$discussionId/': typeof AppOrganizationsOrganizationIdDiscussionsDiscussionIdIndexRoute
  '/organizations/$organizationId/settings/invites/': typeof AppOrganizationsOrganizationIdSettingsInvitesIndexRoute
  '/organizations/$organizationId/settings/people/': typeof AppOrganizationsOrganizationIdSettingsPeopleIndexRoute
  '/organizations/$organizationId/boards/$boardId/$taskId/edit': typeof AppOrganizationsOrganizationIdBoardsBoardIdTaskIdEditRoute
  '/organizations/$organizationId/discussions/$discussionId/$commentId/edit': typeof AppOrganizationsOrganizationIdDiscussionsDiscussionIdCommentIdEditRoute
  '/organizations/$organizationId/settings/people/$userId/edit': typeof AppOrganizationsOrganizationIdSettingsPeopleUserIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/invites/$inviteId': typeof AppInvitesInviteIdRoute
  '/organizations/join': typeof AppOrganizationsJoinRoute
  '/organizations/new': typeof AppOrganizationsNewRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/language': typeof AppSettingsLanguageRoute
  '/settings/theme': typeof AppSettingsThemeRoute
  '/organizations': typeof AppOrganizationsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/organizations/$organizationId/overview': typeof AppOrganizationsOrganizationIdOverviewRoute
  '/organizations/$organizationId': typeof AppOrganizationsOrganizationIdIndexRoute
  '/organizations/$organizationId/boards/new': typeof AppOrganizationsOrganizationIdBoardsNewRoute
  '/organizations/$organizationId/discussions/new': typeof AppOrganizationsOrganizationIdDiscussionsNewRoute
  '/organizations/$organizationId/settings/general': typeof AppOrganizationsOrganizationIdSettingsGeneralRoute
  '/organizations/$organizationId/boards': typeof AppOrganizationsOrganizationIdBoardsIndexRoute
  '/organizations/$organizationId/discussions': typeof AppOrganizationsOrganizationIdDiscussionsIndexRoute
  '/organizations/$organizationId/settings': typeof AppOrganizationsOrganizationIdSettingsIndexRoute
  '/organizations/$organizationId/boards/$boardId/edit': typeof AppOrganizationsOrganizationIdBoardsBoardIdEditRoute
  '/organizations/$organizationId/boards/$boardId/new': typeof AppOrganizationsOrganizationIdBoardsBoardIdNewRoute
  '/organizations/$organizationId/discussions/$discussionId/edit': typeof AppOrganizationsOrganizationIdDiscussionsDiscussionIdEditRoute
  '/organizations/$organizationId/settings/invites/new': typeof AppOrganizationsOrganizationIdSettingsInvitesNewRoute
  '/organizations/$organizationId/boards/$boardId': typeof AppOrganizationsOrganizationIdBoardsBoardIdIndexRoute
  '/organizations/$organizationId/discussions/$discussionId': typeof AppOrganizationsOrganizationIdDiscussionsDiscussionIdIndexRoute
  '/organizations/$organizationId/settings/invites': typeof AppOrganizationsOrganizationIdSettingsInvitesIndexRoute
  '/organizations/$organizationId/settings/people': typeof AppOrganizationsOrganizationIdSettingsPeopleIndexRoute
  '/organizations/$organizationId/boards/$boardId/$taskId/edit': typeof AppOrganizationsOrganizationIdBoardsBoardIdTaskIdEditRoute
  '/organizations/$organizationId/discussions/$discussionId/$commentId/edit': typeof AppOrganizationsOrganizationIdDiscussionsDiscussionIdCommentIdEditRoute
  '/organizations/$organizationId/settings/people/$userId/edit': typeof AppOrganizationsOrganizationIdSettingsPeopleUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/invites/$inviteId': typeof AppInvitesInviteIdRoute
  '/_app/organizations/$organizationId': typeof AppOrganizationsOrganizationIdRouteWithChildren
  '/_app/organizations/join': typeof AppOrganizationsJoinRoute
  '/_app/organizations/new': typeof AppOrganizationsNewRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/language': typeof AppSettingsLanguageRoute
  '/_app/settings/theme': typeof AppSettingsThemeRoute
  '/_app/organizations/': typeof AppOrganizationsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/organizations/$organizationId/overview': typeof AppOrganizationsOrganizationIdOverviewRoute
  '/_app/organizations/$organizationId/': typeof AppOrganizationsOrganizationIdIndexRoute
  '/_app/organizations/$organizationId/boards/new': typeof AppOrganizationsOrganizationIdBoardsNewRoute
  '/_app/organizations/$organizationId/discussions/new': typeof AppOrganizationsOrganizationIdDiscussionsNewRoute
  '/_app/organizations/$organizationId/settings/general': typeof AppOrganizationsOrganizationIdSettingsGeneralRoute
  '/_app/organizations/$organizationId/boards/': typeof AppOrganizationsOrganizationIdBoardsIndexRoute
  '/_app/organizations/$organizationId/discussions/': typeof AppOrganizationsOrganizationIdDiscussionsIndexRoute
  '/_app/organizations/$organizationId/settings/': typeof AppOrganizationsOrganizationIdSettingsIndexRoute
  '/_app/organizations/$organizationId/boards/$boardId/edit': typeof AppOrganizationsOrganizationIdBoardsBoardIdEditRoute
  '/_app/organizations/$organizationId/boards/$boardId/new': typeof AppOrganizationsOrganizationIdBoardsBoardIdNewRoute
  '/_app/organizations/$organizationId/discussions/$discussionId/edit': typeof AppOrganizationsOrganizationIdDiscussionsDiscussionIdEditRoute
  '/_app/organizations/$organizationId/settings/invites/new': typeof AppOrganizationsOrganizationIdSettingsInvitesNewRoute
  '/_app/organizations/$organizationId/boards/$boardId/': typeof AppOrganizationsOrganizationIdBoardsBoardIdIndexRoute
  '/_app/organizations/$organizationId/discussions/$discussionId/': typeof AppOrganizationsOrganizationIdDiscussionsDiscussionIdIndexRoute
  '/_app/organizations/$organizationId/settings/invites/': typeof AppOrganizationsOrganizationIdSettingsInvitesIndexRoute
  '/_app/organizations/$organizationId/settings/people/': typeof AppOrganizationsOrganizationIdSettingsPeopleIndexRoute
  '/_app/organizations/$organizationId/boards/$boardId/$taskId/edit': typeof AppOrganizationsOrganizationIdBoardsBoardIdTaskIdEditRoute
  '/_app/organizations/$organizationId/discussions/$discussionId/$commentId/edit': typeof AppOrganizationsOrganizationIdDiscussionsDiscussionIdCommentIdEditRoute
  '/_app/organizations/$organizationId/settings/people/$userId/edit': typeof AppOrganizationsOrganizationIdSettingsPeopleUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/invites/$inviteId'
    | '/organizations/$organizationId'
    | '/organizations/join'
    | '/organizations/new'
    | '/settings/account'
    | '/settings/language'
    | '/settings/theme'
    | '/organizations/'
    | '/settings/'
    | '/organizations/$organizationId/overview'
    | '/organizations/$organizationId/'
    | '/organizations/$organizationId/boards/new'
    | '/organizations/$organizationId/discussions/new'
    | '/organizations/$organizationId/settings/general'
    | '/organizations/$organizationId/boards/'
    | '/organizations/$organizationId/discussions/'
    | '/organizations/$organizationId/settings/'
    | '/organizations/$organizationId/boards/$boardId/edit'
    | '/organizations/$organizationId/boards/$boardId/new'
    | '/organizations/$organizationId/discussions/$discussionId/edit'
    | '/organizations/$organizationId/settings/invites/new'
    | '/organizations/$organizationId/boards/$boardId/'
    | '/organizations/$organizationId/discussions/$discussionId/'
    | '/organizations/$organizationId/settings/invites/'
    | '/organizations/$organizationId/settings/people/'
    | '/organizations/$organizationId/boards/$boardId/$taskId/edit'
    | '/organizations/$organizationId/discussions/$discussionId/$commentId/edit'
    | '/organizations/$organizationId/settings/people/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/invites/$inviteId'
    | '/organizations/join'
    | '/organizations/new'
    | '/settings/account'
    | '/settings/language'
    | '/settings/theme'
    | '/organizations'
    | '/settings'
    | '/organizations/$organizationId/overview'
    | '/organizations/$organizationId'
    | '/organizations/$organizationId/boards/new'
    | '/organizations/$organizationId/discussions/new'
    | '/organizations/$organizationId/settings/general'
    | '/organizations/$organizationId/boards'
    | '/organizations/$organizationId/discussions'
    | '/organizations/$organizationId/settings'
    | '/organizations/$organizationId/boards/$boardId/edit'
    | '/organizations/$organizationId/boards/$boardId/new'
    | '/organizations/$organizationId/discussions/$discussionId/edit'
    | '/organizations/$organizationId/settings/invites/new'
    | '/organizations/$organizationId/boards/$boardId'
    | '/organizations/$organizationId/discussions/$discussionId'
    | '/organizations/$organizationId/settings/invites'
    | '/organizations/$organizationId/settings/people'
    | '/organizations/$organizationId/boards/$boardId/$taskId/edit'
    | '/organizations/$organizationId/discussions/$discussionId/$commentId/edit'
    | '/organizations/$organizationId/settings/people/$userId/edit'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/settings'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_app/'
    | '/_app/invites/$inviteId'
    | '/_app/organizations/$organizationId'
    | '/_app/organizations/join'
    | '/_app/organizations/new'
    | '/_app/settings/account'
    | '/_app/settings/language'
    | '/_app/settings/theme'
    | '/_app/organizations/'
    | '/_app/settings/'
    | '/_app/organizations/$organizationId/overview'
    | '/_app/organizations/$organizationId/'
    | '/_app/organizations/$organizationId/boards/new'
    | '/_app/organizations/$organizationId/discussions/new'
    | '/_app/organizations/$organizationId/settings/general'
    | '/_app/organizations/$organizationId/boards/'
    | '/_app/organizations/$organizationId/discussions/'
    | '/_app/organizations/$organizationId/settings/'
    | '/_app/organizations/$organizationId/boards/$boardId/edit'
    | '/_app/organizations/$organizationId/boards/$boardId/new'
    | '/_app/organizations/$organizationId/discussions/$discussionId/edit'
    | '/_app/organizations/$organizationId/settings/invites/new'
    | '/_app/organizations/$organizationId/boards/$boardId/'
    | '/_app/organizations/$organizationId/discussions/$discussionId/'
    | '/_app/organizations/$organizationId/settings/invites/'
    | '/_app/organizations/$organizationId/settings/people/'
    | '/_app/organizations/$organizationId/boards/$boardId/$taskId/edit'
    | '/_app/organizations/$organizationId/discussions/$discussionId/$commentId/edit'
    | '/_app/organizations/$organizationId/settings/people/$userId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/organizations/': {
      id: '/_app/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AppOrganizationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/theme': {
      id: '/_app/settings/theme'
      path: '/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof AppSettingsThemeRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/language': {
      id: '/_app/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof AppSettingsLanguageRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/organizations/new': {
      id: '/_app/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof AppOrganizationsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/join': {
      id: '/_app/organizations/join'
      path: '/organizations/join'
      fullPath: '/organizations/join'
      preLoaderRoute: typeof AppOrganizationsJoinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/$organizationId': {
      id: '/_app/organizations/$organizationId'
      path: '/organizations/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invites/$inviteId': {
      id: '/_app/invites/$inviteId'
      path: '/invites/$inviteId'
      fullPath: '/invites/$inviteId'
      preLoaderRoute: typeof AppInvitesInviteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/$organizationId/': {
      id: '/_app/organizations/$organizationId/'
      path: '/'
      fullPath: '/organizations/$organizationId/'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdIndexRouteImport
      parentRoute: typeof AppOrganizationsOrganizationIdRoute
    }
    '/_app/organizations/$organizationId/overview': {
      id: '/_app/organizations/$organizationId/overview'
      path: '/overview'
      fullPath: '/organizations/$organizationId/overview'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdOverviewRouteImport
      parentRoute: typeof AppOrganizationsOrganizationIdRoute
    }
    '/_app/organizations/$organizationId/settings/': {
      id: '/_app/organizations/$organizationId/settings/'
      path: '/settings'
      fullPath: '/organizations/$organizationId/settings/'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdSettingsIndexRouteImport
      parentRoute: typeof AppOrganizationsOrganizationIdRoute
    }
    '/_app/organizations/$organizationId/discussions/': {
      id: '/_app/organizations/$organizationId/discussions/'
      path: '/discussions'
      fullPath: '/organizations/$organizationId/discussions/'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdDiscussionsIndexRouteImport
      parentRoute: typeof AppOrganizationsOrganizationIdRoute
    }
    '/_app/organizations/$organizationId/boards/': {
      id: '/_app/organizations/$organizationId/boards/'
      path: '/boards'
      fullPath: '/organizations/$organizationId/boards/'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdBoardsIndexRouteImport
      parentRoute: typeof AppOrganizationsOrganizationIdRoute
    }
    '/_app/organizations/$organizationId/settings/general': {
      id: '/_app/organizations/$organizationId/settings/general'
      path: '/settings/general'
      fullPath: '/organizations/$organizationId/settings/general'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdSettingsGeneralRouteImport
      parentRoute: typeof AppOrganizationsOrganizationIdRoute
    }
    '/_app/organizations/$organizationId/discussions/new': {
      id: '/_app/organizations/$organizationId/discussions/new'
      path: '/discussions/new'
      fullPath: '/organizations/$organizationId/discussions/new'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdDiscussionsNewRouteImport
      parentRoute: typeof AppOrganizationsOrganizationIdRoute
    }
    '/_app/organizations/$organizationId/boards/new': {
      id: '/_app/organizations/$organizationId/boards/new'
      path: '/boards/new'
      fullPath: '/organizations/$organizationId/boards/new'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdBoardsNewRouteImport
      parentRoute: typeof AppOrganizationsOrganizationIdRoute
    }
    '/_app/organizations/$organizationId/settings/people/': {
      id: '/_app/organizations/$organizationId/settings/people/'
      path: '/settings/people'
      fullPath: '/organizations/$organizationId/settings/people/'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdSettingsPeopleIndexRouteImport
      parentRoute: typeof AppOrganizationsOrganizationIdRoute
    }
    '/_app/organizations/$organizationId/settings/invites/': {
      id: '/_app/organizations/$organizationId/settings/invites/'
      path: '/settings/invites'
      fullPath: '/organizations/$organizationId/settings/invites/'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdSettingsInvitesIndexRouteImport
      parentRoute: typeof AppOrganizationsOrganizationIdRoute
    }
    '/_app/organizations/$organizationId/discussions/$discussionId/': {
      id: '/_app/organizations/$organizationId/discussions/$discussionId/'
      path: '/discussions/$discussionId'
      fullPath: '/organizations/$organizationId/discussions/$discussionId/'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdDiscussionsDiscussionIdIndexRouteImport
      parentRoute: typeof AppOrganizationsOrganizationIdRoute
    }
    '/_app/organizations/$organizationId/boards/$boardId/': {
      id: '/_app/organizations/$organizationId/boards/$boardId/'
      path: '/boards/$boardId'
      fullPath: '/organizations/$organizationId/boards/$boardId/'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdBoardsBoardIdIndexRouteImport
      parentRoute: typeof AppOrganizationsOrganizationIdRoute
    }
    '/_app/organizations/$organizationId/settings/invites/new': {
      id: '/_app/organizations/$organizationId/settings/invites/new'
      path: '/settings/invites/new'
      fullPath: '/organizations/$organizationId/settings/invites/new'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdSettingsInvitesNewRouteImport
      parentRoute: typeof AppOrganizationsOrganizationIdRoute
    }
    '/_app/organizations/$organizationId/discussions/$discussionId/edit': {
      id: '/_app/organizations/$organizationId/discussions/$discussionId/edit'
      path: '/discussions/$discussionId/edit'
      fullPath: '/organizations/$organizationId/discussions/$discussionId/edit'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdDiscussionsDiscussionIdEditRouteImport
      parentRoute: typeof AppOrganizationsOrganizationIdRoute
    }
    '/_app/organizations/$organizationId/boards/$boardId/new': {
      id: '/_app/organizations/$organizationId/boards/$boardId/new'
      path: '/boards/$boardId/new'
      fullPath: '/organizations/$organizationId/boards/$boardId/new'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdBoardsBoardIdNewRouteImport
      parentRoute: typeof AppOrganizationsOrganizationIdRoute
    }
    '/_app/organizations/$organizationId/boards/$boardId/edit': {
      id: '/_app/organizations/$organizationId/boards/$boardId/edit'
      path: '/boards/$boardId/edit'
      fullPath: '/organizations/$organizationId/boards/$boardId/edit'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdBoardsBoardIdEditRouteImport
      parentRoute: typeof AppOrganizationsOrganizationIdRoute
    }
    '/_app/organizations/$organizationId/settings/people/$userId/edit': {
      id: '/_app/organizations/$organizationId/settings/people/$userId/edit'
      path: '/settings/people/$userId/edit'
      fullPath: '/organizations/$organizationId/settings/people/$userId/edit'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdSettingsPeopleUserIdEditRouteImport
      parentRoute: typeof AppOrganizationsOrganizationIdRoute
    }
    '/_app/organizations/$organizationId/discussions/$discussionId/$commentId/edit': {
      id: '/_app/organizations/$organizationId/discussions/$discussionId/$commentId/edit'
      path: '/discussions/$discussionId/$commentId/edit'
      fullPath: '/organizations/$organizationId/discussions/$discussionId/$commentId/edit'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdDiscussionsDiscussionIdCommentIdEditRouteImport
      parentRoute: typeof AppOrganizationsOrganizationIdRoute
    }
    '/_app/organizations/$organizationId/boards/$boardId/$taskId/edit': {
      id: '/_app/organizations/$organizationId/boards/$boardId/$taskId/edit'
      path: '/boards/$boardId/$taskId/edit'
      fullPath: '/organizations/$organizationId/boards/$boardId/$taskId/edit'
      preLoaderRoute: typeof AppOrganizationsOrganizationIdBoardsBoardIdTaskIdEditRouteImport
      parentRoute: typeof AppOrganizationsOrganizationIdRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsLanguageRoute: typeof AppSettingsLanguageRoute
  AppSettingsThemeRoute: typeof AppSettingsThemeRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsLanguageRoute: AppSettingsLanguageRoute,
  AppSettingsThemeRoute: AppSettingsThemeRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppOrganizationsOrganizationIdRouteChildren {
  AppOrganizationsOrganizationIdOverviewRoute: typeof AppOrganizationsOrganizationIdOverviewRoute
  AppOrganizationsOrganizationIdIndexRoute: typeof AppOrganizationsOrganizationIdIndexRoute
  AppOrganizationsOrganizationIdBoardsNewRoute: typeof AppOrganizationsOrganizationIdBoardsNewRoute
  AppOrganizationsOrganizationIdDiscussionsNewRoute: typeof AppOrganizationsOrganizationIdDiscussionsNewRoute
  AppOrganizationsOrganizationIdSettingsGeneralRoute: typeof AppOrganizationsOrganizationIdSettingsGeneralRoute
  AppOrganizationsOrganizationIdBoardsIndexRoute: typeof AppOrganizationsOrganizationIdBoardsIndexRoute
  AppOrganizationsOrganizationIdDiscussionsIndexRoute: typeof AppOrganizationsOrganizationIdDiscussionsIndexRoute
  AppOrganizationsOrganizationIdSettingsIndexRoute: typeof AppOrganizationsOrganizationIdSettingsIndexRoute
  AppOrganizationsOrganizationIdBoardsBoardIdEditRoute: typeof AppOrganizationsOrganizationIdBoardsBoardIdEditRoute
  AppOrganizationsOrganizationIdBoardsBoardIdNewRoute: typeof AppOrganizationsOrganizationIdBoardsBoardIdNewRoute
  AppOrganizationsOrganizationIdDiscussionsDiscussionIdEditRoute: typeof AppOrganizationsOrganizationIdDiscussionsDiscussionIdEditRoute
  AppOrganizationsOrganizationIdSettingsInvitesNewRoute: typeof AppOrganizationsOrganizationIdSettingsInvitesNewRoute
  AppOrganizationsOrganizationIdBoardsBoardIdIndexRoute: typeof AppOrganizationsOrganizationIdBoardsBoardIdIndexRoute
  AppOrganizationsOrganizationIdDiscussionsDiscussionIdIndexRoute: typeof AppOrganizationsOrganizationIdDiscussionsDiscussionIdIndexRoute
  AppOrganizationsOrganizationIdSettingsInvitesIndexRoute: typeof AppOrganizationsOrganizationIdSettingsInvitesIndexRoute
  AppOrganizationsOrganizationIdSettingsPeopleIndexRoute: typeof AppOrganizationsOrganizationIdSettingsPeopleIndexRoute
  AppOrganizationsOrganizationIdBoardsBoardIdTaskIdEditRoute: typeof AppOrganizationsOrganizationIdBoardsBoardIdTaskIdEditRoute
  AppOrganizationsOrganizationIdDiscussionsDiscussionIdCommentIdEditRoute: typeof AppOrganizationsOrganizationIdDiscussionsDiscussionIdCommentIdEditRoute
  AppOrganizationsOrganizationIdSettingsPeopleUserIdEditRoute: typeof AppOrganizationsOrganizationIdSettingsPeopleUserIdEditRoute
}

const AppOrganizationsOrganizationIdRouteChildren: AppOrganizationsOrganizationIdRouteChildren =
  {
    AppOrganizationsOrganizationIdOverviewRoute:
      AppOrganizationsOrganizationIdOverviewRoute,
    AppOrganizationsOrganizationIdIndexRoute:
      AppOrganizationsOrganizationIdIndexRoute,
    AppOrganizationsOrganizationIdBoardsNewRoute:
      AppOrganizationsOrganizationIdBoardsNewRoute,
    AppOrganizationsOrganizationIdDiscussionsNewRoute:
      AppOrganizationsOrganizationIdDiscussionsNewRoute,
    AppOrganizationsOrganizationIdSettingsGeneralRoute:
      AppOrganizationsOrganizationIdSettingsGeneralRoute,
    AppOrganizationsOrganizationIdBoardsIndexRoute:
      AppOrganizationsOrganizationIdBoardsIndexRoute,
    AppOrganizationsOrganizationIdDiscussionsIndexRoute:
      AppOrganizationsOrganizationIdDiscussionsIndexRoute,
    AppOrganizationsOrganizationIdSettingsIndexRoute:
      AppOrganizationsOrganizationIdSettingsIndexRoute,
    AppOrganizationsOrganizationIdBoardsBoardIdEditRoute:
      AppOrganizationsOrganizationIdBoardsBoardIdEditRoute,
    AppOrganizationsOrganizationIdBoardsBoardIdNewRoute:
      AppOrganizationsOrganizationIdBoardsBoardIdNewRoute,
    AppOrganizationsOrganizationIdDiscussionsDiscussionIdEditRoute:
      AppOrganizationsOrganizationIdDiscussionsDiscussionIdEditRoute,
    AppOrganizationsOrganizationIdSettingsInvitesNewRoute:
      AppOrganizationsOrganizationIdSettingsInvitesNewRoute,
    AppOrganizationsOrganizationIdBoardsBoardIdIndexRoute:
      AppOrganizationsOrganizationIdBoardsBoardIdIndexRoute,
    AppOrganizationsOrganizationIdDiscussionsDiscussionIdIndexRoute:
      AppOrganizationsOrganizationIdDiscussionsDiscussionIdIndexRoute,
    AppOrganizationsOrganizationIdSettingsInvitesIndexRoute:
      AppOrganizationsOrganizationIdSettingsInvitesIndexRoute,
    AppOrganizationsOrganizationIdSettingsPeopleIndexRoute:
      AppOrganizationsOrganizationIdSettingsPeopleIndexRoute,
    AppOrganizationsOrganizationIdBoardsBoardIdTaskIdEditRoute:
      AppOrganizationsOrganizationIdBoardsBoardIdTaskIdEditRoute,
    AppOrganizationsOrganizationIdDiscussionsDiscussionIdCommentIdEditRoute:
      AppOrganizationsOrganizationIdDiscussionsDiscussionIdCommentIdEditRoute,
    AppOrganizationsOrganizationIdSettingsPeopleUserIdEditRoute:
      AppOrganizationsOrganizationIdSettingsPeopleUserIdEditRoute,
  }

const AppOrganizationsOrganizationIdRouteWithChildren =
  AppOrganizationsOrganizationIdRoute._addFileChildren(
    AppOrganizationsOrganizationIdRouteChildren,
  )

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppInvitesInviteIdRoute: typeof AppInvitesInviteIdRoute
  AppOrganizationsOrganizationIdRoute: typeof AppOrganizationsOrganizationIdRouteWithChildren
  AppOrganizationsJoinRoute: typeof AppOrganizationsJoinRoute
  AppOrganizationsNewRoute: typeof AppOrganizationsNewRoute
  AppOrganizationsIndexRoute: typeof AppOrganizationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppInvitesInviteIdRoute: AppInvitesInviteIdRoute,
  AppOrganizationsOrganizationIdRoute:
    AppOrganizationsOrganizationIdRouteWithChildren,
  AppOrganizationsJoinRoute: AppOrganizationsJoinRoute,
  AppOrganizationsNewRoute: AppOrganizationsNewRoute,
  AppOrganizationsIndexRoute: AppOrganizationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
